# Generated by Django 3.0.5 on 2020-04-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid19CountriesApi',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='covid19Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='', help_text='Country Name', max_length=100)),
                ('codeName', models.CharField(default='covid19', editable=False, max_length=100)),
                ('totalCases', models.IntegerField(blank=True)),
                ('totalDeath', models.IntegerField(blank=True)),
                ('totalRecovered', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='covid19Locals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('locals', models.CharField(default='', help_text='Local Name', max_length=100)),
                ('codeName', models.CharField(default='covid19', editable=False, max_length=100)),
                ('totalCases', models.IntegerField(blank=True)),
                ('totalDeath', models.IntegerField(blank=True)),
                ('totalRecovered', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='covid19LocalsApi',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='covid19MAHA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('mahaArea', models.CharField(default='', help_text='Maha area Name', max_length=100)),
                ('codeName', models.CharField(default='covid19', editable=False, max_length=100)),
                ('totalCases', models.IntegerField(blank=True)),
                ('totalDeath', models.IntegerField(blank=True)),
                ('totalRecovered', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='covid19MahaApi',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='covid19States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('states', models.CharField(default='', help_text='State Name', max_length=100)),
                ('codeName', models.CharField(default='covid19', editable=False, max_length=100)),
                ('totalCases', models.IntegerField(blank=True)),
                ('totalDeath', models.IntegerField(blank=True)),
                ('totalRecovered', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='covid19StatesApi',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
