# Generated by Django 3.0.7 on 2020-06-21 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('Summary', wagtail.core.fields.RichTextField()),
                ('Project_Lead', models.CharField(default='Nagindra', max_length=100)),
                ('Project_status', models.BooleanField(default=False)),
                ('rating_proj', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('Summary', wagtail.core.fields.RichTextField()),
                ('due_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('select_project', models.ForeignKey(help_text='Select Your Project', on_delete=django.db.models.deletion.CASCADE, to='project_mnt.Project')),
            ],
        ),
    ]
